name: frontend-deployment-workflow
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
      - name: Create .env file
        run: echo "${{ secrets.ENV_PROD }}" > ./packages/frontend/.env
      - name: Install dependencies
        run: yarn install --frozon-lockfile
      - name: Build & export frontend
        run: yarn frontend:build
      - name: Unit Test
        run: yarn frontend-deployment:test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: AWS CDK deploy
        run: yarn frontend-deployment:deploy
